/api/v1/services/availability:
  get:
    tags: [ Disponibilidad ]
    summary: Obtener disponibilidad de productos por fecha
    parameters:
      - name: date
        in: query
        required: true
        schema:
          type: string
          format: date
        description: Fecha para consultar (YYYY-MM-DD)
      - name: products
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: array
          items:
            $ref: '#/components/schemas/Product'
        description: Lista de productos a verificar
    responses:
      200:
        description: Disponibilidad por horario
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AvailabilityResponse'
      400:
        description: Error de validación
      500:
        description: Error interno del servidor
